URL_SHORTENER_SERVICE_HOST = ENV["URL_SHORTENER_SERVICE_HOST"] || "http://localhost:3001"
#URL_SHORTENER_SERVICE_HOST = ENV["URL_SHORTENER_SERVICE_HOST"] || "https://mighty-hamlet-47944.herokuapp.com/"
