default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: share_tracker_dev
  username: share_tracker
  password: password
  
test:
  <<: *default
  database: share_tracker_test
  username: share_tracker
  password: password
