default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: small_url_dev
  username: small_url
  password: password
  
test:
  <<: *default
  database: small_url_test
  username: small_url
  password: password
